### ISSUE TITLE
Hassio Tor addon [[(localize('ui.panel.page-authorize.initializing')]]

### ISSUE THREAD

**Issue by warlock916** [hassio-addons/addon-tor#10]
Hello i have just installed hass.io on raspberry i was adding tor addon

Connection ok, but loginpage doesn't load it remains 

[[(localize('ui.panel.page-authorize.initializing')]]

It should appear login hass.io page

**Comment by Maikl3** [comment]
It looks like the same problem.
Thor establishes a connection, but authorization in HA fails.

The same error in the TOR browser on Windows. And on android in orbot.
 You're about to give access to your Home Assistant instance.

Logging in with Home Assistant Local.
Error: Message format incorrect: required key not provided @ data['client_id']

config

{
  "log_level": "info",
  "socks": false,
  "hidden_services": true,
  "stealth": false,
  "client_names": [],
  "ports": [
    "8123"
  ]
}

log home assistant

Log Details (ERROR)
Mon Feb 25 2019 02:05:25 GMT+0300 (RTZ 2 (зима))
Data does not match schema: required key not provided @ data['client_id']

**Comment by anrada73** [comment]
i have a same problem

**Comment by frenck** [comment]
The Tor Browser is based on Firefox. This is an upstream issue in Home Assistant.

Report: home-assistant/home-assistant-polymer#2859
PR with Fix: home-assistant/home-assistant-polymer#2860

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/home-assistant-polymer/pull/2860

**Comment by frenck** [comment]
Nice! Closing issue.
