### ISSUE TITLE
Tor uses tor v2 urls

### ISSUE THREAD

**Issue by Minecodes** [hassio-addons/addon-tor#107]
On my raspberry pi the homeassistant addon uses tor v2 urls like "http://expyuzz4wqqyqhjn.onion/" (source: [support.torproject.org/onionservices](https://support.torproject.org/onionservices/)), but doesn't use tor v3 urls. Please fix it, because it's migrating at the moment to v3.

**Comment by foo-calls-bar** [comment]
A patch for this issue was recently pulled into the main branch. You can pull it yourself and manually install as a local add-on to begin using v3 URLs right now (as long as you don't use stealth mode, the patch for which is still pending, I believe) if you can't wait for the next official release.

**Comment by foo-calls-bar** [comment]
> On my raspberry pi the homeassistant addon uses tor v2 urls like "http://expyuzz4wqqyqhjn.onion/" (source: [support.torproject.org/onionservices](https://support.torproject.org/onionservices/)), but doesn't use tor v3 urls. Please fix it, because it's migrating at the moment to v3.

A patch for this issue was recently pulled into the main branch. You can pull it yourself and manually install as a local add-on to begin using v3 URLs right now (as long as you don't use stealth mode, the patch for which is still pending, I believe) if you can't wait for the next official release.
