### ISSUE TITLE
Note: Tor Broser v11 (current release) doesn't work with addon-tor, and workaround.

### ISSUE THREAD

**Issue by tsat-psv** [hassio-addons/addon-tor#119]
Just a note to anyone having issues with the latest tor browser, it does no longer support urls from this addon. Meaning if you donwload tor today from the latest stable release you can't use this addon.

A workaround until this addon is updated is to download the latest v10 version of the browser instead here: https://archive.torproject.org/tor-package-archive/torbrowser/10.5.10/

**Comment by frenck** [comment]
This is not a bulletin board

**Comment by tsat-psv** [comment]
Sure, but this is what shows up when people google the issue. It was only to help people that might experience problems, not intended to offend or hurt anyone's feelings.
