### ISSUE TITLE
Add-on is not working in stealth mode after upgrade to 2.0.0

### ISSUE THREAD

**Issue by akasma74** [hassio-addons/addon-tor#12]
# Problem/Motivation
After upgrading from 1.6.0 to 2.0.0 add-on is not working in stealth mode (errors in log and cannot connect to it)
 
## Expected behaviour
work as usual

## Actual behavior

Add-on is showed as running, but there are errors in log and I get Unable to connect trying to reach my Hass.io via Orfox

## Steps to reproduce
I run Hass.io 0.89.0.

My config
````
{
  "socks": false,
  "hidden_services": true,
  "stealth": true,
  "client_names": [
    "a",
    "b"
  ],
  "ports": [
    "8123"
  ],
  "log_level": "info"
}
````

in log I can see

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] 10-tor: applying... 
> [fix-attrs.d] 10-tor: exited 0.
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 00-banner.sh: executing... 
> -----------------------------------------------------------
>  Hass.io Add-on: Tor
>  Protect your privacy and access Home Assistant via Tor.
> -----------------------------------------------------------
>  Add-on version: 2.0.0
>  You are running the latest version of this add-on.
>  System: HassOS 1.13  (armv7 / raspberrypi3)
>  Home Assistant version: 0.89.0
>  Supervisor version: 150
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in e.g, GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> [cont-init.d] 00-banner.sh: exited 0.
> [cont-init.d] 01-log-level.sh: executing... 
> Log level is set to INFO
> [cont-init.d] 01-log-level.sh: exited 0.
> [cont-init.d] 10-requirements.sh: executing... 
> [cont-init.d] 10-requirements.sh: exited 0.
> [cont-init.d] 20-dirs.sh: executing... 
> [cont-init.d] 20-dirs.sh: exited 0.
> [cont-init.d] 50-tor-log.sh: executing... 
> [cont-init.d] 50-tor-log.sh: exited 0.
> [cont-init.d] 51-tor-socks.sh: executing... 
> [cont-init.d] 51-tor-socks.sh: exited 0.
> [cont-init.d] 52-tor-services.sh: executing... 
> [cont-init.d] 52-tor-services.sh: exited 0.
> [cont-init.d] 90-hostname.sh: executing... 
> [13:59:52] INFO: Starting Tor temporarly...
> [cont-init.d] 90-hostname.sh: exited 1.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] 99-message.sh: executing... 
> -----------------------------------------------------------
>                 Oops! Something went wrong.
> 
>  We are so sorry, but something went terribly wrong when
>  starting or running this add-on.
>  
>  Be sure to check the log above, line by line, for hints.
> -----------------------------------------------------------
> [cont-finish.d] 99-message.sh: exited 0.
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.

**Comment by Maikl3** [comment]
Same problem after upgrading to 2.0.0

**Comment by guandalf** [comment]
Same here...

Add-on version: 2.0.0
System: HassOS 2.11  (armv7 / raspberrypi3)
Home Assistant version: 0.90.1
Supervisor version: 150
[cont-init.d] 90-hostname.sh: executing... 
[21:24:40] INFO: Starting Tor temporarly...
[cont-init.d] 90-hostname.sh: exited 1.

**Comment by mwesten** [comment]
Same problem here.... no more Tor when using secret=true

**Comment by pawelkw** [comment]
Same here.

Full log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-tor: applying... 
[fix-attrs.d] 10-tor: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Tor
 Protect your privacy and access Home Assistant via Tor.
-----------------------------------------------------------
 Add-on version: 2.0.0
 You are running the latest version of this add-on.
 System: HassOS 2.10  (armv7 / raspberrypi2)
 Home Assistant version: 0.90.0
 Supervisor version: 152
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in e.g, GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-dirs.sh: executing... 
[cont-init.d] 20-dirs.sh: exited 0.
[cont-init.d] 50-tor-log.sh: executing... 
[cont-init.d] 50-tor-log.sh: exited 0.
[cont-init.d] 51-tor-socks.sh: executing... 
[cont-init.d] 51-tor-socks.sh: exited 0.
[cont-init.d] 52-tor-services.sh: executing... 
[cont-init.d] 52-tor-services.sh: exited 0.
[cont-init.d] 90-hostname.sh: executing... 
[11:40:15] INFO: Starting Tor temporarly...
[cont-init.d] 90-hostname.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
s6-nuke: fatal: unable to kill: No such process
```

Running on RasPi 2.

**Comment by Maikl3** [comment]
Problem same here :(
I tried to reinstall the addon. Stealth mode does not work.

Config
```
{
  "socks": false,
  "hidden_services": true,
  "stealth": true,
  "client_names": [
    "mnefs"
  ],
  "ports": [
    "8123"
  ]
}
```

Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-tor: applying... 
[fix-attrs.d] 10-tor: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Tor
 Protect your privacy and access Home Assistant via Tor.
-----------------------------------------------------------
 Add-on version: 2.0.0
 You are running the latest version of this add-on.
 System: HassOS 2.11  (armv7 / raspberrypi3)
 Home Assistant version: 0.90.2
 Supervisor version: 152
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in e.g, GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-dirs.sh: executing... 
[cont-init.d] 20-dirs.sh: exited 0.
[cont-init.d] 50-tor-log.sh: executing... 
[cont-init.d] 50-tor-log.sh: exited 0.
[cont-init.d] 51-tor-socks.sh: executing... 
[cont-init.d] 51-tor-socks.sh: exited 0.
[cont-init.d] 52-tor-services.sh: executing... 
[cont-init.d] 52-tor-services.sh: exited 0.
[cont-init.d] 90-hostname.sh: executing... 
[13:31:57] INFO: Starting Tor temporarly...
[cont-init.d] 90-hostname.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by akasma74** [comment]
0.91.0, same issue :(
how can we re-open the issue?

**Comment by guandalf** [comment]
But it has not been released yet; how did you manage @akasma74 and @Maikl3 to test it?

**Comment by akasma74** [comment]
If they merged it and closed the issue, I assumed it's already on the latest release

**Comment by frenck** [comment]
Incorrect assumption @akasma74

**Comment by akasma74** [comment]
I understand it now.
However, is it possible in the future to give others a hint regarding when the fix will be released when closing an issue? Could save all of us from situations like this.

**Comment by frenck** [comment]
@akasma74 I leave a message when it is released and in case of doubt, check the releases tab of the github project, which shows all the details. Thanks.

**Comment by akasma74** [comment]
Ok, got it. Thought it required a fix somewhere in HA.
So we're waiting for the next Tor ADD-ON release..
