### ISSUE TITLE
v2 service does not work anymore with latest Tor (v 11).

### ISSUE THREAD

**Issue by sergeymaysak** [hassio-addons/addon-tor#120]
# Problem/Motivation

I use the default configuration of hidden onion service hassio plugin with v2 service (no stealth). With enabled automatic update of Tor, I've got Tor updated to version 11. Tor v 11 reports error on attempt to access my .onion site:
Invalid Onionsite Address

The provided onionsite address is invalid. Please check that you entered it correctly.

Details: 0xF6 — The provided .onion address is invalid. This error is returned due to one of the following reasons: the address checksum doesn't match, the ed25519 public key is invalid, or the encoding is invalid.

## Expected behavior

My .onion site should be opened by Tor normally.

## Actual behavior

Tor refuses to open v2 .onion site with error.

## Steps to reproduce

1. Install latest version of Tor (v 11 on Nov 14)
2. Try to open v2 based .onion site 
3. Observe error

## Proposed changes

Please add support for v3 hidden service in hassio and provide way/details/steps how to upgrade existing v2 service to v3 service.

**Comment by Psykopear** [comment]
See the [answer](https://github.com/hassio-addons/addon-tor/issues/107#issuecomment-959750500) by foo-calls-bar on #107 issue
