### ISSUE TITLE
Onion v3 not in /etc/tor/torrc

### ISSUE THREAD

**Issue by richardsj** [hassio-addons/addon-tor#129]
# Problem/Motivation

TOR no longer works with the production version (3.0.5) of this addon.

## Expected behavior

TOR can generate v3 onions for Hass but the docker container does not allow /etc/tor/torrc to be edited, in fact it is generated by a bash script that has "2" as the version number hard coded

## Actual behavior

Does not work with current production/stable version of TOR

This
`echo 'HiddenServiceVersion 3' >> "$torrc" `
is not in production

## Steps to reproduce

Install HassOS, add TOR addon, go to to TOR address generated in Logs, error

## Proposed changes

Allow this to be a switch/option in Configuration for the addon OR just push the damn 3 to production

**Comment by Psykopear** [comment]
A fix has been proposed in #105, see the discussion there.
We are waiting for a review from the maintainers.

**Comment by ChrisSutton123** [comment]
Waited so long for fix to be "officially" verified. 
Have installed patch as local addon. Works fine.
