### ISSUE TITLE
about privacy/encription

### ISSUE THREAD

**Issue by 50494554524F** [hassio-addons/addon-tor#151]
i just started to study tor and your add-on because i'm using a mobile connection (behind a nat) 

and this add-on seems faster to setup instead of managing a vpn...

just a doubt/confirm... is the internet traffic encrypted?! 

if i embed a camera streaming in homeassistant, could anyone access/intercept the video and see if no one is at home?!

thanks

**Comment by frenck** [comment]
> is the internet traffic encrypted?!

![image](https://user-images.githubusercontent.com/195327/204224953-3477b16a-b5f4-4a70-ac65-29fe4b4a7481.png)

It is the nature of Tor. Read more about Tor on their website:

https://www.torproject.org/about/history/

../Frenck
