### ISSUE TITLE
idea: publish .onion domain as a sensor in HA

### ISSUE THREAD

**Issue by Cooper-Dale** [hassio-addons/addon-tor#18]
# Problem/Motivation

One is not able to determine .oninon address / domain without restarting the addon. It would be nice to trigger automatoins when there is a new domain name ir the sensor is present.

## Expected behavior

new sensor in home assistant

## Actual behavior

domain is not published

## Proposed changes
- please create a new sensor, and option in settings for that behavior - similar to https://github.com/sabeechen/hassio-google-drive-backup
- what is right .onion doman or address? 

<blockquote><img src="https://avatars0.githubusercontent.com/u/21026774?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/sabeechen/hassio-google-drive-backup">sabeechen/hassio-google-drive-backup</a></strong></div><div>Automatically create and sync Hass.io snapshots into Google Drive - sabeechen/hassio-google-drive-backup</div></blockquote>

**Comment by frenck** [comment]
IMHO, the behavior created by the Google Drive add-on is wrong. But that is just my opinion.

Regarding the suggestion for this add-on, adding that would require to open up HA to the add-on, just for the cause of sending in a static address? The address is only generated once, and does not change during the lifetime of the add-on.

I really don't see the value of setting up a sensor. A sensor monitors something, this is not monitoring, this is misusing a functionality to become a notebook.

Nevertheless, thank you for your suggestion :+1:
