### ISSUE TITLE
Add FireFox onion config to documentation

### ISSUE THREAD

**Issue by primetomas** [hassio-addons/addon-tor#2]
Thanks for a great add-on, and great documentation!

# Problem/Motivation

> I could not use FireFox over the Tor network to access the .onion site

## Expected behavior

> Hass.io was available in ForeFox

## Actual behavior

> FireFox said the server did not respond

## Steps to reproduce

> Set up Orbot according to the (excellent) docs, and use FireFox on Android with Orbot in full VPN mode. Try to access your .onion site with hass.io

## Proposed changes
Add a note after configuring Orbot that:

If you want to use FireFox to access .onion domains you need to enable this in FireFix settings. Type "about:config" in the address bar and open the advanced settings. Search for "onion" to find the setting "network.dns.blockDotOnion". Toggle the setting so it is set to "false". Now you should be able to access the .onion site created by the Tor add-on using FireFox.

**Comment by frenck** [comment]
Great addition indeed @primetomas!

I've marked this as something we should do. Feel free to open a PR to add it yourself (if your up to it! 😉 )

**Comment by primetomas** [comment]
Thanks for the quick feedback. Sorry for the delay. Pull request created.

**Comment by frenck** [comment]
Thanks! Merged in!
