### ISSUE TITLE
Support for injection of a key for a custom (vanity) .onion service name

### ISSUE THREAD

**Issue by nktl** [hassio-addons/addon-tor#21]
Thank you for this great addon!

It would be fantastic if addon configuration allowed to define custom key for a particular .onion service name, for instance generated with Scallion (https://github.com/lachesis/scallion) - instead of relying on autogenerated one.

This will allow usage of more user-friendly, vanity names - and preservation of the key/ .onion service name between re-installations, etc.

<blockquote><img src="https://avatars1.githubusercontent.com/u/347481?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/lachesis/scallion">lachesis/scallion</a></strong></div><div>GPU-based Onion Hash generator. Contribute to lachesis/scallion development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
You can, all data is stored in the `/ssl` folder, which you can customize.
