### ISSUE TITLE
2.3.0 fails to start in stealth mode

### ISSUE THREAD

**Issue by froz** [hassio-addons/addon-tor#22]
# Problem/Motivation
2.3.0 fails to start if stealth mode is enabled.  Nothing is logged to indicate what might be going wrong other than that the script 90-hostname.sh never finishes.

## Expected behavior
The add-on will write out the hidden service files and finish the startup process,

## Actual behavior
The add-on waits forever for the hidden service files, specifically "hostname" to exist, but they never get created.

## Steps to reproduce
config:
```
hidden_services: true
stealth: true
client_names:
  - client1
  - client2
```

## Proposed changes
unknown

## Additional Information
```
Add-on version: 2.3.0
You are running the latest version of this add-on.
System: Ubuntu 18.04.4 LTS  (aarch64 / odroid-n2)
Home Assistant Core: 0.106.2
Home Assistant Supervisor: 201
```
Last lines of log:
```
[cont-init.d] 52-tor-services.sh: executing... 
[cont-init.d] 52-tor-services.sh: exited 0.
[cont-init.d] 90-hostname.sh: executing... 
[07:00:56] INFO: Starting Tor temporarly...
```

**Comment by froz** [comment]
Stale, but still an issue.

**Comment by froz** [comment]
Same

**Comment by RascleMB** [comment]
New to HA and especially the Tor Add-On.  Having the same Issue.  Performing Additional Troubleshooting I have found that if I only have 1 Client Configured then the Add-On will Start and Operate.  As soon as I add a Second client_name and Restart it give the following:


```
[cont-init.d] 90-hostname.sh: executing... 
[18:05:20] INFO: Starting Tor temporarly...
[cont-init.d] 90-hostname.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.

```
 All other Scripts (.sh) in log entries above this exit with Status 0 (normal).

**Comment by RascleMB** [comment]
HA & Tor Add-On Specs/Data:

```
-----------------------------------------------------------
 Add-on: Tor
 Protect your privacy and access Home Assistant via Tor.
-----------------------------------------------------------
 Add-on version: 2.4.0
 You are running the latest version of this add-on.
 System: HassOS 4.11  (armv7 / raspberrypi4)
 Home Assistant Core: 0.112.4
 Home Assistant Supervisor: 229
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------


```

**Comment by RascleMB** [comment]
Though having been 7 Months since this was opened without a single response from Frenck, it appears he may be MIA.  :(

And though I do some programming and work in IT, unfortunately I am way to new to HA/Tor/Add-Ons to even try to work out a fix.

**Comment by froz** [comment]
Still the same

**Comment by xakiru** [comment]
same issue
