### ISSUE TITLE
Plugin run as root

### ISSUE THREAD

**Issue by aasselin** [hassio-addons/addon-tor#244]
# Problem/Motivation

The service complains that it is launched as root:
Nov 12 22:16:50.000 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.

## Expected behavior

It would be top to avoid this warning, running services as root is typically dangerous

## Actual behavior

Service run as root

## Steps to reproduce

Use default configuration

## Proposed changes

Thank you very much for all your efforts.

**Comment by frenck** [comment]
Yup, however, add-ons are isolated containers. It is the preferred method for the Home Assistant end.

Nevertheless, thanks for your suggestion.

../Frenck
