### ISSUE TITLE
Support for v3 hidden services

### ISSUE THREAD

**Issue by khicks** [hassio-addons/addon-tor#83]
This is a re-opening of issue #54, which is closed and locked.

The Tor Project is [deprecating v2 hidden services](https://support.torproject.org/onionservices/#v2-deprecation), and the Tor Browser will stop supporting them in July 2021 (next month).

I highly recommend changing the hidden services config to use v3 hidden services to keep this add-on functional.

**Comment by ghgeiger** [comment]
I'm not sure that I will have physical access to my HA instance that has tor running on it prior to this deprecation being enacted. Can anyone provide guidance on how to update torrc remotely (through a tor connection) to prepare for v3?

**Comment by khicks** [comment]
@ghgeiger It's a very easy fix. All you have to do is change this line in your torrc:

    - HiddenServiceVersion 2
    + HiddenServiceVersion 3

It's been a while since I've tested, but you may also need to (back up and) delete your v2 keys from your `HiddenServiceDir`. Given that it's literally a one-bit change to fix, I would normally open a PR myself. However, I'm not super qualified to get it all tested.

I'll be petitioning to have this add-on removed from the list of HA community add-ons once Tor Browser updates to remove support for v2 hidden services. People shouldn't have to downgrade to an insecure version of Tor Browser just to reach their HA instance. If you still need a hidden service, I would recommend setting up a RPi or VM to run Tor and configure your torrc to direct to Home Assistant. For anyone curious, it would look like this:

    HiddenServiceDir /var/lib/tor/home_assistant
    HiddenServicePort 8123 192.168.1.100:8123

Of course you would change `192.168.1.100` to your Home Assistant IP, but you get the idea. The aforementioned `HiddenServiceVersion 3` line is implied in recent releases of Tor. Once that's configured and you restarted the Tor service, get your onion address from `/var/lib/tor/home_assistant/hostname`.

**Comment by khicks** [comment]
@ghgeiger Reading that back, I didn't mean for "It's a very easy fix" to be condescending to you. 😅 I wanted to highlight how relatively simple it would be for the add-on maintainer to push a change to get this fixed. Heck, I wouldn't mind having to completely re-install the add-on if it means it can continue to work with Tor Browser.

If the developer is pushing his Patreon page within the Home Assistant add-on store, he should at least be up for fixing this relatively simple yet critical issue.

**Comment by Konrad162** [comment]
Hi, @frenck 
Please, could you let me know, do you plan to update this HiddenServiceVersion?

**Comment by protei300** [comment]
Hello everyone!

Also started to have some issues using HiddenService v2... at least now i cannot connect to file editor.. it says unauthorized...

**Comment by foo-calls-bar** [comment]
> This is a re-opening of issue #54, which is closed and locked.
> 
> The Tor Project is [deprecating v2 hidden services](https://support.torproject.org/onionservices/#v2-deprecation), and the Tor Browser will stop supporting them in July 2021 (next month).
> 
> I highly recommend changing the hidden services config to use v3 hidden services to keep this add-on functional.

I submitted a pull request to patch this a couple weeks ago and it's still pending. If an administrator would please review it so we can get this essential issue fixed ASAP I think it would be greatly appreciated by all. Otherwise this absolutely essential addon will soon be totally obsolete. HA user security will suffer immensely if that happens and people are forced to forward ports and advertise the service. I get that users can configure a native Tor installation to accomplish the same thing, but that is far too complicated for all but the most technically inclined of end users, especially on HA OS raspberry pi installations, which lacks even a native package manager.

**Comment by ghgeiger** [comment]
The most recent release has definitely *not* resolved this issue. 

@khicks I know that this would normally be an easy fix, but I'm running HA on a supervised RPI installation & I'm not sure that I have access to the directory that torrc is located. isn't it in its own container? The log refers to "/etc/tor/torrc", but I can't access that from the file editor, or at least I can't access the proper /etc dir that torrc is located. I guess what I'm asking is there an easy way to access torrc inside of its add-on container from afar? SSH add-on + nano? 

Sorry if I'm showing my ignorance on the inner workings of Home Assistant &/or docker containers.

**Comment by frenck** [comment]
Currently on dev.
